<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>True</UseWindowsForms>
	<NoWarn>$(NoWarn);NU1701</NoWarn>
	<AssemblyVersion>1.0.50.26254</AssemblyVersion>

	<Title>HandyUI.WinForms</Title>
	<Description>Platform-agnostic Code-Only C# UI framework powered by SkiaSharp.</Description>
	<PackageReleaseNotes>Release notes for:
 - HandyUI.Core v1.0.2x (v1.0.2x instead of v1.0.29 to account for automatic versioning.)
 - HandyUI.WinForms v1.0.3x (v1.0.3x instead of v1.0.33 to account for automatic versioning.)

New Features &amp; UI Controls
 - Added new controls: ImageButton, ImageLabel, ToggleButton, ImageToggleButton, and Frame
 - Introduced the HandyForm subclass in HandyUI.WinForms
 - Added animations to select controls
 - Added control parenting support

Improvements &amp; Bug Fixes
 - Fixed UI Renderer bugs
 - Improved retained mode positioning</PackageReleaseNotes>
	<PackageTags>ui;framework;skiasharp;code-only;gui;rendering</PackageTags>
	<PackageId>HandyUI.WinForms</PackageId>
	<Version>$(AssemblyVersion)</Version>
	<Authors>davpnuser</Authors>
	<PackageIcon>HandyUI-Logo.png</PackageIcon>
	<NeutralLanguage>en</NeutralLanguage>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/davpnuser/HandyUI/</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageProjectUrl>https://github.com/davpnuser/HandyUI/</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Ubeyde\Downloads\HandyUI-Logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="4.152.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HandyUI.Core\HandyUI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="HandyUI-Logo.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
